export const ITEM_CART_ADD = 'ITEM_CART_ADD';
export const ITEM_CART_REMOVE = 'ITEM_CART_REMOVE';
export const ITEM_CART_RESET = 'ITEM_CART_RESET';
export const ITEM_CART_FULL_REMOVE = 'ITEM_CART_FULL_REMOVE';
